# Generated by Django 5.2.12 on 2026-05-26 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core_linked_records_app", "0004_rename_pidxpath_to_pidpath"),
        (
            "core_main_app",
            "0014_data_processing_module",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="pidpath",
            name="template",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="core_main_app.template",
            ),
        ),
    ]
